import '@/styles/globals.css';
import vazirFont from '@/constants/localFont';

export const metadata = {
  title: 'Welcome to capi-admin',
  description: 'Generated by create-nx-workspace',
};
export default function RootLayout({ children }) {
  return (
    <html
      lang="fa"
      dir="rtl"
      suppressHydrationWarning
      className={`${vazirFont.variable} font-sans`}
    >
      <body>{children}</body>
    </html>
  );
}
